var ar={
  "welcome":"مرحباً بك",
  "askForOrder":"اطلب ما تريد وسيصلك طلبك الى باب منزلك",
  "login":"تسجيل الدخول",
  "country":"الدولة",
  "phone":"رقم الجوال",
  "pass":"كلمة المرور",
  "forgetPass":"نسيت كلمة المرور؟",
  "signup":"انشاء حساب",
  "skip":"تخطي",
  "loading":"جارٍ الطلب..",
  "username":"اسم المستخدم",
  "confirmPass":"اعادة كلمة المرور",
  "newPass":"كلمة المرور الجديدة",
  "acceptPolicy":"الموافقة على شروط الاستخدام",
  "useTerms":" شروط الاستخدام",
  "accept":"اوافق",
  "haveAccount":"لديك حساب؟ سجل الدخول",
  "haven'tAccount":"مستخدم جديد؟ انضم الان",
  "verifyAccount":"تفعيل الحساب",
  "verify":"تفعيل",
  "enterCodeToVerify":"برجاء ادخال الكود لتفعيل حسابكم",
  "resendCode":"لم يصلك الكود؟ اعادة الارسال 1:45",
  "resetPass":"استرداد كلمة المرور",
  "enterPhone":"برجاء ادخال رقم الجوال المُسجل",
  "next":"التالي",
  "verificationCode":"ادخال الكود",
  "enterSentCode":"برجاء ادخال الكود المرسل في الرسائل النصية",
  "chooseYourCountry":"اختر بلدك",
  "somethingWentWrong":"عفوا حدث خطا ما",
};