var en={
  "welcome":"Welcome back",
  "askForOrder":"Ask for what you want and your order will be delivered to your doorstep",
  "login":"Login",
  "country":"Country",
  "phone":"Phone",
  "pass":"Password",
  "forgetPass":"Forget password?",
  "signup":"Sign Up",
  "skip":"Skip",
  "loading":"Loading..",
  "username":"User Name",
  "confirmPass":"Confirm password",
  "newPass":"New password",
  "acceptPolicy":"Accept policy terms",
  "useTerms":"Use terms",
  "accept":"Accept",
  "haveAccount":"Have an account? login",
  "haven'tAccount":"New Member? join now",
  "verifyAccount":"Verify account",
  "verify":"Verify",
  "enterCodeToVerify":"Please enter the verification code",
  "resendCode":"Didn't receive code? send again 1:45",
  "resetPass":"Reset password",
  "enterPhone":"Please enter your phone number",
  "next":"Next",
  "verificationCode":"Verification code",
  "enterSentCode":"Please enter sent code",
  "chooseYourCountry":"Choose your country",
  "somethingWentWrong":"Sorry, something went wrong",
};